urls.py
from django.urls import path, include

from . import views

app_name = 'qliksense'

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),

    path('licencia/', views.LicenciasListView.as_view(), name='list_licencia'),
    path('licencia/nueva/', views.LicenciasCreateView.as_view(), name='create_licencia'),
    path('licencia/ver/<uuid:pk>', views.LicenciasDetailView.as_view(), name='detail_licencia'),
    path('licencia/actualizar/<uuid:pk>', views.LicenciasUpdateView.as_view(), name='update_licencia'),
    path('licencia/eliminar/<uuid:pk>', views.LicenciasDeleteView.as_view(), name='delete_licencia'),

    path('area/', views.AreaListView.as_view(), name='list_area'),
    path('area/nueva/', views.AreaCreateView.as_view(), name='create_area'),
    path('area/ver/<uuid:pk>', views.AreaDetailView.as_view(), name='detail_area'),
    path('area/actualizar/<uuid:pk>', views.AreaUpdateView.as_view(), name='update_area'),
    path('area/eliminar/<uuid:pk>', views.AreaDeleteView.as_view(), name='delete_area'),

    path('area_tipolicencia/nueva/', views.Area_TipoLicenciaFormView.as_view(), name='create_areatipo'),
    path('area_tipolicencia/actualizar/<uuid:pk>', views.Area_TipoLicenciaUpdateView.as_view(), name='update_areatipo'),
    path('area_tipolicencia/eliminar/<uuid:pk>', views.Area_TipoLicenciaDeleteView.as_view(), name='delete_areatipo'),

    path('usuario/', views.UsuarioListView.as_view(), name='list_usuario'),
    path('usuario/nuevo/', views.UsuarioCreateView.as_view(), name='create_usuario'),
    path('usuario/actualizar/<uuid:pk>', views.UsuarioUpdateView.as_view(), name='update_usuario'),
    path('usuario/eliminar/<uuid:pk>', views.UsuarioDeleteView.as_view(), name='delete_usuario'),

    path('stream/', views.StreamListView.as_view(), name='list_stream'),
    path('stream/ver/<uuid:pk>', views.StreamDetailView.as_view(), name='detail_stream'),
    path('qlikapi/recargar/', views.refresh_all, name='refresh_all_data'),

    path('modelo/ver/<uuid:pk>', views.ModelDetailView.as_view(), name='detail_modelo'),
]


    




    
    

models.py
import uuid

from django.conf import settings
from django.db import models
from django.db.models.constraints import UniqueConstraint
from django.utils.translation import gettext as _
from django.urls import reverse_lazy

from simple_history.models import HistoricalRecords

from usuarios.personal_views import Configuracion

###
conf = Configuracion()
###

class TipoLicencia(models.Model):
    '''
        Tipo de licencias contratadas para hacer uso de la herramienta.
    '''
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    descripcion = models.CharField(_('Descripción'), max_length = 120, unique = True)
    cantidad    = models.PositiveSmallIntegerField(verbose_name = _('Cantidad'))

    history     = HistoricalRecords(user_model=settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.descripcion

    def licencias_asignadas(self):
        cantidad = Area_TipoLicencia.objects.filter(tipo=self, vigente=True)\
            .aggregate(models.Sum('cantidad'))['cantidad__sum']
        return cantidad if cantidad else 0

    def licencias_no_asignadas(self):
            return self.cantidad - self.licencias_asignadas()

    def url_create():
        return reverse_lazy('qliksense:create_licencia')

    def url_detail(self):
        return reverse_lazy('qliksense:detail_licencia', kwargs={'pk': self.id})

    def url_update(self):
        return reverse_lazy('qliksense:update_licencia', kwargs={'pk': self.id})

    def url_delete(self):
        if Area_TipoLicencia.objects.filter(tipo = self.id).count()>0:
            return None
        return reverse_lazy('qliksense:delete_licencia', kwargs={'pk': self.id})

class Area(models.Model):
    '''
        Area responsable del uso de la licencia
    '''
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre      = models.CharField(_('Nombre'), max_length = 120, unique = True)

    history     = HistoricalRecords(user_model=settings.AUTH_USER_MODEL)

    def __str__(self):
        return f'{self.nombre}'

    def url_create():
        return reverse_lazy('qliksense:create_area')

    def url_detail(self):
        return reverse_lazy('qliksense:detail_area', kwargs={'pk': self.id})

    def url_update(self):
        return reverse_lazy('qliksense:update_area', kwargs={'pk': self.id})

    def url_delete(self):
        if Area_TipoLicencia.objects.filter(area=self.id):
            return None
        return reverse_lazy('qliksense:delete_area', kwargs={'pk': self.id})

class Area_TipoLicencia(models.Model):
    '''
        Asignacion de tipos de licencia por área, para determinar los costos
        por su adquisición.
    '''
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    cantidad    = models.PositiveSmallIntegerField(verbose_name=_('Cantidad'))
    vigente     = models.BooleanField(_('Estado'), default=True)

    tipo        = models.ForeignKey(TipoLicencia, on_delete = models.RESTRICT)
    area        = models.ForeignKey(Area, on_delete = models.RESTRICT)

    history     = HistoricalRecords(user_model=settings.AUTH_USER_MODEL)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['tipo', 'area'], name='unq_atl_area_tipo')
        ]

    def __str__(self):
        return f'{self.area.nombre} / {self.tipo.descripcion} ({self.licencias_disponibles()})'

    def licencias_asignadas(self):
        return Usuario.objects.filter(vigente=True, area_tipo=self).count()

    def licencias_disponibles(self):
        return self.cantidad - self.licencias_asignadas()

    def url_update(self):
        return reverse_lazy('qliksense:update_areatipo', kwargs={'pk': self.id})

    def url_delete(self):
        if Usuario.objects.filter(area_tipo = self.id).count()>0:
            return None
        return reverse_lazy('qliksense:delete_areatipo', kwargs={'pk': self.id})

class Usuario (models.Model):
    '''
        Usuario con licencia asignada
    '''
    TIPOS = [
        ('USR', 'USR'),
        ('OUT', 'OUT'),
    ]
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tipo        = models.CharField(_('Tipo de usuario'), choices=TIPOS, max_length=3)
    # def_tipo_display()
    codigo      = models.PositiveIntegerField(verbose_name=_('Código'))
    nombre      = models.CharField(_('Nombre'), max_length=120)
    extension   = models.CharField(_('Extensión'), max_length=6, blank=True, null=True)
    correo      = models.CharField(_('Correo'), max_length=120, blank=True, null=True)
    vigente     = models.BooleanField(_('Estado'), default=True)
    creacion    = models.DateField(_('Ingreso'), auto_now_add=True)
    actualizacion = models.DateField(_('Actualización'), auto_now=True)

    area_tipo   = models.ForeignKey(Area_TipoLicencia, verbose_name=_('Area/Tipo'), on_delete=models.RESTRICT)

    history     = HistoricalRecords(excluded_fields=['creacion', 'actualizacion'], user_model=settings.AUTH_USER_MODEL)

    class Meta:
        constraints = [
            UniqueConstraint(fields=['tipo', 'codigo'], name='unq_usr_tipo_codigo'),
        ]

    def __str__(self):
        return f'{self.nombre} ({self.get_usuario_dominio()})'

    def get_usuario_dominio(self):
        return f'{self.tipo}{str(self.codigo).zfill(6)}'

    def url_create():
        return reverse_lazy('qliksense:create_usuario')

    def url_update(self):
        return reverse_lazy('qliksense:update_usuario', kwargs={'pk': self.id})

    def url_delete(self):
        if Usuario.objects.filter(area_tipo = self.id).count()>0:
            return None
        return reverse_lazy('qliksense:delete_usuario', kwargs={'pk': self.id})


class Stream (models.Model):
    '''
        Streams de Qlik Sense
    '''
    id          = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre      = models.CharField(_('Nombre'), max_length = 120, unique = True)
    
    history     = HistoricalRecords(user_model=settings.AUTH_USER_MODEL)

    def __str__(self):
        return f'{self.nombre}'

    def qlik_url(self):
        return conf.get_value('qliksense', 'qs_webproxy').join(f'stream/{self.qlik_id}')

    def url_refresh(self):
        if self:
            return reverse_lazy('qliksense:refresh_stream', kwargs={'pk': self.id})
        return reverse_lazy('qliksense:refresh_stream')

    def url_create():
        return reverse_lazy('qliksense:create_stream')

    def url_detail(self):
        return reverse_lazy('qliksense:detail_stream', kwargs={'pk': self.id})

class Modelo(models.Model):
    ''' 
        Modelo de datos 
        Registrado en Qlik Sense
    '''
    id      = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    nombre  = models.CharField(verbose_name=_('Nombre'), max_length=90)
    descripcion = models.CharField(verbose_name=_('Descripción'), max_length=210, blank=True)
    stream  = models.ForeignKey(Stream, verbose_name=_('Stream'), on_delete=models.RESTRICT, related_name='modelo_stream')

    history     = HistoricalRecords(user_model=settings.AUTH_USER_MODEL)

    def __str__(self):
        return self.nombre

    def get_resumen(self, max_length=60):
        return f'{self.descripcion[:max_length]}...'

    def url_detail(self):
        return reverse_lazy('qliksense:detail_modelo', kwargs={'pk': self.id})

templates/base_qliksense.html
{% extends 'base.html' %}
{% load static i18n %}

<!-- Navbar -->
{% block navbar %}

{% if user.is_authenticated %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    {% translate "Licenciamiento" %}
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'qliksense:list_licencia' %}">{% translate "Tipo de licencias" %}</a></li>
    <li><a class="dropdown-item" href="{% url 'qliksense:create_licencia' %}">{% translate "Nuevo tipo de licencias" %}</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="{% url 'qliksense:list_area' %}">{% translate "Áreas responsables" %}</a></li>
    <li><a class="dropdown-item" href="{% url 'qliksense:create_area' %}">{% translate "Nueva Área" %}</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="{% url 'qliksense:list_usuario' %}">{% translate "Listar Usuarios" %}</a></li>
    <li><a class="dropdown-item" href="{% url 'qliksense:create_usuario' %}">{% translate "Nuevo Usuario" %}</a></li>
  </ul>
</li>
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    {% translate "Qlik Sense" %}
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'qliksense:list_stream' %}">Listar Streams</a></li>
  </ul>
</li>
{% endif %}
{% endblock %}
<!-- Navbar -->

templates/qliksense_menu.html
{% load static i18n %}

{% if user.is_authenticated %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    {% translate "Licenciamiento" %}
  </a>
  <ul class="dropdown-menu">
    {% if perms.qliksense.view_tipolicencia %}
    <li><a class="dropdown-item" href="{% url 'qliksense:list_licencia' %}">{% translate "Tipo de licencias" %}</a></li>
    <li><hr class="dropdown-divider"></li>
    {% endif %}
    {% if perms.qliksense.view_area %}
    <li><a class="dropdown-item" href="{% url 'qliksense:list_area' %}">{% translate "Áreas responsables" %}</a></li>
    <li><hr class="dropdown-divider"></li>
    {% endif %}
    {% if perms.qliksense.view_usuario %}
    <li><a class="dropdown-item" href="{% url 'qliksense:list_usuario' %}">{% translate "Listar Usuarios" %}</a></li>
    {% endif %}
  </ul>
</li>
  {% if perms.qliksense.view_stream %}
<li class="nav-item dropdown">
  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    {% translate "Qlik Sense" %}
  </a>
  <ul class="dropdown-menu">
    <li><a class="dropdown-item" href="{% url 'qliksense:list_stream' %}">Listar Streams</a></li>
  </ul>
</li>
  {% endif %}
{% endif %}