urls.py
from django.urls import path, include

from . import views

app_name = 'qliksense'

urlpatterns = [
    path('', views.IndexTemplateView.as_view(), name='index'),

    path('licencia/', views.LicenciasListView.as_view(), name='list_licencia'),
    path('licencia/nueva/', views.LicenciasCreateView.as_view(), name='create_licencia'),
    path('licencia/ver/<uuid:pk>', views.LicenciasDetailView.as_view(), name='detail_licencia'),
    path('licencia/actualizar/<uuid:pk>', views.LicenciasUpdateView.as_view(), name='update_licencia'),
    path('licencia/eliminar/<uuid:pk>', views.LicenciasDeleteView.as_view(), name='delete_licencia'),

    path('area/', views.AreaListView.as_view(), name='list_area'),
    path('area/nueva/', views.AreaCreateView.as_view(), name='create_area'),
    path('area/ver/<uuid:pk>', views.AreaDetailView.as_view(), name='detail_area'),
    path('area/actualizar/<uuid:pk>', views.AreaUpdateView.as_view(), name='update_area'),
    path('area/eliminar/<uuid:pk>', views.AreaDeleteView.as_view(), name='delete_area'),

    path('area_tipolicencia/nueva/', views.Area_TipoLicenciaFormView.as_view(), name='create_areatipo'),
    path('area_tipolicencia/actualizar/<uuid:pk>', views.Area_TipoLicenciaUpdateView.as_view(), name='update_areatipo'),
    path('area_tipolicencia/eliminar/<uuid:pk>', views.Area_TipoLicenciaDeleteView.as_view(), name='delete_areatipo'),

    path('usuario/', views.UsuarioListView.as_view(), name='list_usuario'),
    path('usuario/nuevo/', views.UsuarioCreateView.as_view(), name='create_usuario'),
    path('usuario/actualizar/<uuid:pk>', views.UsuarioUpdateView.as_view(), name='update_usuario'),
    path('usuario/eliminar/<uuid:pk>', views.UsuarioDeleteView.as_view(), name='delete_usuario'),

    path('stream/', views.StreamListView.as_view(), name='list_stream'),
    path('stream/ver/<uuid:pk>', views.StreamDetailView.as_view(), name='detail_stream'),
    path('qlikapi/recargar/', views.refresh_all, name='refresh_all_data'),

    path('modelo/ver/<uuid:pk>', views.ModelDetailView.as_view(), name='detail_modelo'),
]


    




    
    

templates/qliksense/lists.html
{% extends 'base_qliksense.html' %}
{% load static fields_tags %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <h1>{{ title }}</h1>

    {% if object_list %}
    <table class="table">
      <thead>
        <tr>
          {% if campos.enumerar > -1 %}
          <th scope="col">#</th>
          {% endif %}

          {% for campo in campos.lista %}
          <th scope="col">{% get_verbose_field_name object_list.0 campo %}</th>
          {% endfor %}

          {% if campos.opciones %}
          <th scope="col">{{ campos.opciones }}</th>
          {% endif %}
        </tr>
      </thead>

      <tbody>
        {% for object in object_list %}
        <tr>
          {% if campos.enumerar > -1 %}
          <th scope="row">
            {% if campos.enumerar == 0 %}
              {{ forloop.counter0 }}
            {% else %}
              {{ forloop.counter }}
            {% endif %}
          </th>
          {% endif %}

          {% for campo in campos.lista %}
          <td>{% get_object_value object campo %}</td>
          {% endfor %}

          {% if campos.opciones %}
          <th scope="col">
            <a href="{% url 'qliksense:detail_licencia' object.id %}" class="btn btn-primary">
              <img src="{% static 'images/qs_detail.png' %}" alt={{ opciones.detail }} height="25px">
            </a>
            <a href="{% url 'qliksense:update_licencia' object.id %}" class="btn btn-primary">
              <img src="{% static 'images/qs_update.png' %}" alt={{ opciones.update }} height="25px">
            </a>
            <a href="{% url 'qliksense:delete_licencia' object.id %}" class="btn btn-danger">
              <img src="{% static 'images/qs_delete.png' %}" alt={{ opciones.delete }} height="25px">
            </a>
          </th>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>

    {% else %}
    <div class="alert alert-warning" role="alert">
      {{ mensaje.vacio }}
    </div>
    {% endif %}

{% endblock %}